"""
Django settings for AppWeb project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

LOGIN_URL = '/login'

PAYPAL_CLIENT_ID = 'AfshFEaRQVRxjQb04tmaykNwABiZnr6GOMOohJmrNukvEJ4AHtkDgxnvR0OJ6_xVelYSUBDQtBuA777r'
PAYPAL_CLIENT_SECRET = 'EKHdwQzbAMQAEYiz3QVHh6_lA5X4S4Vt0HzitnCcuWSdsKcEAz7EXXL4ag58OFu6dCoQcg_Hs_mPguV1'
PAYPAL_MODE = 'sandbox'  # Mode test

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-5x^p(#4*q@8kq)ws3nu@kfcp+0150j2m&at75#jjp5(q*h($ao'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']




# Application 

 
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'inscription',
    'django.contrib.humanize',
    
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
  
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # 'inscription.middleware.AuthRequiredMiddleware', 
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

LOGIN_URL = '/login/'

ROOT_URLCONF = 'AppWeb.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ["templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
              
               
            ],
        },
    },
]

WSGI_APPLICATION = 'AppWeb.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

 

 

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Définir le bon fuseau horaire pour le Burundi
TIME_ZONE = 'Africa/Bujumbura'  # UTC+2


USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CSRF_TRUSTED_ORIGINS = [
    'http://127.0.0.1:8000',  # 🔹 Ajoute ton domaine local
    'http://localhost:8000',   # 🔹 Si tu utilises "localhost"
'https://appweb-main-2.onrender.com',
]

CSRF_COOKIE_SECURE = False  # 🔹 Met à False en local (sinon il exige HTTPS)

# Configuration des médias
import os

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Configuration des fichiers
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB

# Email configuration
# Email configuration
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # Pour développement
DEFAULT_FROM_EMAIL = 'infojosnetent@gmail.com'  # Email expéditeur
CONTACT_EMAIL = 'danielnibangodriver1@gmail.com'  # Email destinataire