# Generated by Django 5.1.7 on 2025-05-19 17:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0002_conversation_message_statutmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_confirmation', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de paiement'), ('confirme', 'Confirmé'), ('annule', 'Annulé'), ('termine', 'Terminé')], default='en_attente', max_length=20)),
                ('paiement_effectue', models.BooleanField(default=False)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('mode_paiement', models.CharField(blank=True, max_length=50)),
                ('reference_paiement', models.CharField(blank=True, max_length=100)),
                ('apprenant', models.ForeignKey(limit_choices_to={'profile__role': 'apprenant'}, on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to=settings.AUTH_USER_MODEL)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='inscription.cours')),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
                'ordering': ['-date_inscription'],
                'unique_together': {('apprenant', 'cours')},
            },
        ),
        migrations.DeleteModel(
            name='Paiement',
        ),
    ]
