# Generated by Django 5.1.7 on 2025-05-19 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0003_inscription_delete_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='heure',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
