# Generated by Django 5.1.7 on 2025-05-19 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0004_cours_heure'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_paiement', models.CharField(choices=[('mobile_money', 'Mobile Money'), ('carte_bancaire', 'Carte Bancaire')], max_length=20)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('operateur', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('nom_carte', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_carte', models.CharField(blank=True, max_length=16, null=True)),
                ('date_expiration', models.CharField(blank=True, max_length=5, null=True)),
                ('cvv', models.CharField(blank=True, max_length=4, null=True)),
                ('reference_paiement', models.CharField(blank=True, max_length=100, null=True)),
                ('paiement_effectue', models.BooleanField(default=False)),
                ('statut', models.CharField(default='en_attente', max_length=20)),
                ('apprenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.cours')),
                ('formateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inscription.formateur')),
            ],
        ),
    ]
